import type { Metadata } from "next";

import { ogImagePath, ogNames, OG_SIZE } from "@/lib/og-paths";
import { keywordsFor, SITE_KEYWORDS } from "@/lib/seo";
import { absoluteUrl, canonicalPath, siteConfig, siteVerification } from "@/lib/site-config";

/**
 * Centralised metadata construction.
 *
 * Every route builds its metadata through `createMetadata` so titles, canonical
 * URLs, Open Graph tags and social images are derived from the same inputs and
 * can never drift apart.
 *
 * Social images are passed explicitly rather than picked up from Next's
 * `opengraph-image` file convention, because that convention emits extensionless
 * files and cannot vary its alt text per slug. See `lib/og.tsx`.
 */

/** Resolves a card name into the tags both Open Graph and Twitter expect. */
function imageTags(name: string, alt: string) {
  return [
    {
      url: absoluteUrl(ogImagePath(name)),
      width: OG_SIZE.width,
      height: OG_SIZE.height,
      alt,
      type: "image/png",
    },
  ];
}

type CreateMetadataInput = {
  title: string;
  description: string;
  /** Internal path; normalised to the canonical trailing-slash form. */
  path: string;
  /** `article` adds published/modified times and author attribution. */
  type?: "website" | "article";
  publishedTime?: string;
  modifiedTime?: string;
  authors?: string[];
  section?: string;
  tags?: string[];
  /** Extra keywords, or a category/hub slug looked up in `CATEGORY_KEYWORDS`. */
  keywords?: string | readonly string[];
  /** Only for genuinely non-indexable pages (e.g. search results). */
  noindex?: boolean;
  /**
   * Skips the `… | Hamzify` template. Used by the homepage, whose title already
   * carries the brand and would otherwise repeat it.
   */
  titleIsAbsolute?: boolean;
  /** Card name from `ogNames`. Falls back to the site card. */
  image?: { name: string; alt: string };
};

export function createMetadata({
  title,
  description,
  path,
  type = "website",
  publishedTime,
  modifiedTime,
  authors,
  section,
  tags,
  keywords,
  noindex = false,
  titleIsAbsolute = false,
  image,
}: CreateMetadataInput): Metadata {
  const url = absoluteUrl(path);
  const images = imageTags(
    image?.name ?? ogNames.site,
    image?.alt ?? `${siteConfig.name} — ${siteConfig.tagline}`,
  );
  const mergedKeywords = keywordsFor(SITE_KEYWORDS, keywords);

  return {
    title: titleIsAbsolute ? { absolute: title } : title,
    description,
    keywords: mergedKeywords.length ? mergedKeywords : undefined,
    alternates: { canonical: url },
    robots: noindex
      ? { index: false, follow: true }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
    openGraph: {
      type: type === "article" ? "article" : "website",
      url,
      siteName: siteConfig.name,
      title,
      description,
      locale: siteConfig.locale,
      images,
      ...(type === "article"
        ? {
            publishedTime,
            modifiedTime: modifiedTime ?? publishedTime,
            authors,
            section,
            tags,
          }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      site: siteConfig.twitterHandle,
      creator: siteConfig.twitterHandle,
      images,
    },
  };
}

/** Root metadata. Everything else inherits and overrides from here. */
export const rootMetadata: Metadata = {
  metadataBase: new URL(siteConfig.url),
  title: {
    default: siteConfig.defaultTitle,
    template: siteConfig.titleTemplate,
  },
  description: siteConfig.description,
  applicationName: siteConfig.name,
  keywords: [...SITE_KEYWORDS],
  alternates: {
    canonical: absoluteUrl("/"),
    types: {
      "application/rss+xml": [
        { url: absoluteUrl("/rss.xml"), title: `${siteConfig.name} — RSS` },
      ],
      "text/plain": [
        { url: absoluteUrl("/llms.txt"), title: `${siteConfig.name} — llms.txt` },
      ],
    },
  },
  manifest: canonicalPath("/manifest.webmanifest"),
  icons: {
    // `icon.svg` is picked up from the app directory automatically; iOS needs a
    // raster icon, which is generated by the /og route.
    apple: [
      {
        url: siteConfig.brand.appleTouchIcon,
        sizes: "180x180",
        type: "image/png",
      },
    ],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    url: absoluteUrl("/"),
    siteName: siteConfig.name,
    title: siteConfig.defaultTitle,
    description: siteConfig.description,
    locale: siteConfig.locale,
    images: imageTags(
      ogNames.site,
      `${siteConfig.name} — ${siteConfig.tagline}`,
    ),
  },
  twitter: {
    card: "summary_large_image",
    site: siteConfig.twitterHandle,
    creator: siteConfig.twitterHandle,
    title: siteConfig.defaultTitle,
    description: siteConfig.description,
    images: imageTags(
      ogNames.site,
      `${siteConfig.name} — ${siteConfig.tagline}`,
    ),
  },
  verification: {
    google: siteVerification.google,
    other: siteVerification.bing
      ? { "msvalidate.01": siteVerification.bing }
      : undefined,
  },
  formatDetection: { telephone: false, address: false, email: false },
  category: "technology",
};
